# Generated by Django 2.1.5 on 2019-04-02 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('accounts', '0002_auto_20190402_2043'),
    ]

    operations = [
    #    migrations.RemoveField(
    #        model_name='user',
    #        name='user_ptr',
    #    ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
