# Generated by Django 2.1.5 on 2019-04-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('accounts', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('username', models.CharField(max_length=30)),
            ],
        ),
    #    migrations.RemoveField(
    #        model_name='user',
    #        name='user_ptr',
    #    ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
